server:
  port: 5555

spring:
  application:
    name: zuulservice
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:9999


eureka:
  instance:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes, refresh, busrefresh


zuul:
  ignored-services: memberservice, workservice
  prefix: /api
  routes:
    memberservice: /my-member/**
    workservice: /my-work/**
