server:
  port: 8761

spring:
  application:
    name: eureka-server2


eureka:
  instance:
    hostname: eureka-server2
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1:8762/eureka/
    registry-fetch-interval-seconds: 10
  server:
    response-cache-update-interval-ms: 100
