server:
  port: 8761

spring:
  application:
    name: eureka-server2


eureka:
  instance:
    hostname: eureka-server2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1:8762/eureka/
